name: guardrail
baseurl: ''
description: Principled code generation from OpenAPI specifications
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.53.0
org: com.twilio
markdown: kramdown
