name: guardrail
baseurl: ''
description: Principled code generation from OpenAPI specifications
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.52.0-1-gaa49640
org: com.twilio
markdown: kramdown
