name: guardrail
baseurl: ''
description: Principled code generation from OpenAPI specifications
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.51.0-56-g37b336e
org: com.twilio
markdown: kramdown
