openapi: 3.0.2
info:
  title: Character Encoding Tests (Response InputStream)
  version: 1.0.0
paths:
  /formData:
    post:
      x-jvm-package: charEncReqStream
      operationId: sendFormData
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - str
              properties:
                str:
                  type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        500:
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /textPlain:
    post:
      x-jvm-package: charEncRespStream
      operationId: sendTextPlain
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                x-java-type: java.io.InputStream
        500:
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /pojo:
    post:
      x-jvm-package: charEncRespStream
      operationId: sendPojo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pojo"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pojo"
        500:
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Pojo:
      type: object
      required:
        - str
      properties:
        str:
          type: string
