openapi: 3.0.2
info:
  title: Ensure required+default work together
  version: 1.0.0
paths:
  /foo:
    post:
      operationId: doFoo
      parameters:
        - name: p1
          in: query
          required: false
          schema:
            type: integer
            format: int64
            default: 300
      responses:
        200:
          description: OK
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          type: integer
          format: int32
          default: 400
