swagger: "2.0"
info:
  title: "may the host and schemes be optional?"
  version: "1.0.1"
basePath: "/v1"
paths:
  /foo:
    get:
      operationId: "getFoo"
      responses:
        200:
          description: OK
