swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
definitions:
  Kernel:
    description: Kernel information
    required:
      - id
    properties:
      id:
        type: string
        format: uuid
        description: uuid of kernel
