openapi: 3.0.1
info:
  version: 1.0.0
components:
  schemas:
    Foo:
      type: object
      required:
        - customArray
        - refArray
      properties:
        customArray:
          type: array
          x-scala-array-type: cats.data.NonEmptyList
          items:
            type: object
            x-jvm-type: Bar
        refArray:
          $ref: '#/components/schemas/Baz'
    Bar:
      type: object
      required:
        - a
      properties:
        a:
          type: integer
          format: int64
    Baz:
      type: array
      x-scala-array-type: cats.data.NonEmptyList
      items:
        $ref: '#/components/schemas/Bar'
