openapi: 3.0.1
info:
  title: Whatever
  version: 1.0.0
servers:
  - url: 'http://localhost:1234'
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: OK
          headers:
            X-Required-Header:
              required: true
              schema:
                type: string
            X-Optional-Header:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
  /bar:
    get:
      operationId: getBar
      responses:
        '204':
          description: "No Content"
          headers:
            X-Required-Header:
              required: true
              schema:
                type: string
            X-Optional-Header:
              schema:
                type: string
components:
  schemas:
    Foo:
      type: object
      properties:
        message:
          type: string
