swagger: "2.0"
info:
  title: Sample API
  description: Random API spec to facilitate code generation
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /users:
    get:
      operationId: getUsers
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          $ref: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      name:
        type: string
