swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
definitions:
  TestObject:
    type: object
    required:
      - required
      - required-nullable
    properties:
      required:
        type: string
      required-nullable:
        type: string
        x-nullable: true
      optional:
        type: string
        x-nullable: false
      optional-nullable:
        type: string
        x-nullable: true
      legacy:
        type: string
