openapi: 3.0.1
info:
  title: "Custom types don't work for array items"
  version: 1.0.0
paths: {}
components:
  schemas:
    Foo:
      type: object
      properties:
        customArray:
          type: array
          items:
            type: object
            x-jvm-type: Bar
        customMap:
          type: object
          additionalProperties:
            type: string
            x-jvm-type: Bar
    Bar:
      type: object
      properties:
        a:
          type: integer
          format: int64
