openapi: 3.0.1
info:
  title: Whatever
  version: 1.0.0
paths: {}
components:
  schemas:
    SimpleMap:
      type: object
      required:
        - simple_obj
        - simple_str
      properties:
        simple_obj:
          type: object
          additionalProperties:
            type: object
        simple_str:
          type: object
          additionalProperties:
            type: string
        just_obj:
          type: object
    FooMapValues:
      type: object
      required:
        - foo
        - bar
      properties:
        foo:
          type: string
        bar:
          type: integer
          format: int32
    Foo:
      type: object
      required:
        - stuff
      properties:
        stuff:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/FooMapValues"
    BarMap:
      type: object
      additionalProperties:
        type: integer
        format: int64
    Bar:
      type: object
      required:
        - stuff
      properties:
        stuff:
          $ref: "#/components/schemas/BarMap"
    BarMapOfMap:
      type: object
      required:
        - stuff
      properties:
        stuff:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/BarMap"
