openapi: 3.0.0
info:
  title: Whatever
  version: 1.0.0
servers:
  - url: //localhost:1234
paths:
  /foo:
    post:
      operationId: doFoo
      x-jvm-package: foo
      parameters:
        - in: query
          name: long
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/defLong"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/defLong"
components:
  schemas:
    defLong:
      type: integer
      format: int64
    defArrayLong:
      type: array
      items:
        type: integer
        format: int64
    defArrayArrayLong:
      type: array
      items:
        $ref: "#/components/schemas/defArrayLong"
    propRef:
      type: object
      required:
        - arrayArray
      properties:
        param:
          $ref: "#/components/schemas/defLong"
        array:
          $ref: "#/components/schemas/defArrayLong"
        arrayArray:
          $ref: "#/components/schemas/defArrayArrayLong"
