openapi: 3.0.2
info:
  title: Test for security support
  version: 1.0.0
paths:
  /foo:
    post:
      x-jvm-package: auth
      operationId: doFoo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: string
      security: []

  /bar:
    post:
      x-jvm-package: auth
      operationId: doBar
      requestBody:
        required: true
        content:
          application/sdp:
            schema:
              type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: string

security:
  - basic:
    - "bar:basic"

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
