openapi: 3.0.1
info:
  version: 1.0.0
paths: {}
produces:
  - application/json
consumes:
  - application/json
components:
  schemas:
    Base:
      type: object
      required:
        - polytype
      properties:
        polytype:
          type: string
      discriminator:
        propertyName: polytype
        mapping:
          this_is_a: A
          this_is_b: "#/components/schemas/B"
    A:
      allOf:
        - $ref: "#/components/schemas/Base"
        - type: object
          required:
            - some_a
          properties:
            some_a:
              type: integer
              format: int32
    B:
      allOf:
        - $ref: "#/components/schemas/Base"
        - type: object
          required:
            - some_b
          properties:
            some_b:
              type: string
    C:
      allOf:
        - $ref: "#/components/schemas/Base"
        - type: object
          required:
            - some_c
          properties:
            some_c:
              type: number
              format: double
    DiscrimEnum:
      type: string
      enum:
        - some-value-one
        - another-value
        - yet-another-value
    EnumBase:
      type: object
      required:
        - polytype
      properties:
        polytype:
          $ref: "#/components/schemas/DiscrimEnum"
      discriminator:
        propertyName: polytype
        mapping:
          some-value-one: EnumA
          another-value: EnumB
          yet-another-value: EnumC
    EnumA:
      allOf:
        - $ref: "#/components/schemas/EnumBase"
        - type: object
          required:
            - some_a
          properties:
            some_a:
              type: integer
              format: int32
    EnumB:
      allOf:
        - $ref: "#/components/schemas/EnumBase"
        - type: object
          required:
            - some_b
          properties:
            some_b:
              type: string
    EnumC:
      allOf:
        - $ref: "#/components/schemas/EnumBase"
        - type: object
          required:
            - some_c
          properties:
            some_c:
              type: number
              format: double
