openapi: 3.0.1
info:
  title: Whatever
  version: 1.0.0
servers:
  - url: 'http://localhost:1234'
components:
  schemas:
    Foo:
      type: object
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: OK
          headers:
            X-Required-Header:
              required: true
              schema:
                type: string
            X-Optional-Header:
              schema:
                type: string
          schema:
            $ref: '#/definitions/Foo'
        '204':
          description: "No Content"
          headers:
            X-Required-Header:
              required: true
              schema:
                type: string
            X-Optional-Header:
              schema:
                type: string
