swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
definitions:
  Address:
    type: object
    properties:
      line1:
        type: string
      line2:
        type: string
      line3:
        type: string
paths:
  /address:
    get:
      operationId: getAddresses
      x-jvm-package: addresses
      produces:
        - application/json
      responses:
        '200':
          description: OK
          type: array
          items:
            $ref: '#/definitions/Address'
        '404':
          description: Not found
  /address/{id}:
    get:
      operationId: getAddress
      x-jvm-package: addresses
      produces:
        - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Address'
        '404':
          description: Not found
