name: Publish website

on:
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.0'
      - name: Install microsite deps
        run: |
          gem update --system
          gem install sass
          gem install jekyll -v 4.0.0
      - name: Print versions
        run: |
          java -version
          gpg --version
          ruby --version
          jekyll --version
      - name: Update website
        run: sbt microsite/makeMicrosite microsite/publishMicrosite
