name: Publish website

on:
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: ruby/setup-ruby@v1.66.1
        with:
          bundler-cache: true
      - name: Install microsite deps
        run: |
          bundle install --jobs 4 --retry 3
      - name: Print versions
        env:
          RUBYOPT: '-rbundler/setup'  # Tricks ruby executables to recognize bundler configuration
        run: |
          java -version
          gpg --version
          ruby --version || true
          jekyll --version || true
      - name: Update website
        env:
          RUBYOPT: '-rbundler/setup'  # Tricks ruby executables to recognize bundler configuration
          MICROSITE_PUBLISH_TOKEN: ${{ secrets.MICROSITE_PUBLISH_TOKEN }}
        run: sbt microsite/makeMicrosite microsite/publishMicrosite
