name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  scala-steward-label:
    runs-on: ubuntu-20.04
    if: context.issue.owner == 'scala-steward'
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['chore']
            })
  publish:
    name: Draft release
    needs: []
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
