name: Release

on:
  release:
    types:
      - released
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: ruby/setup-ruby@v1.66.1
        with:
          ruby-version: '2.6'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install microsite deps
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          echo "$PWD/vendor/bundle/bin" >> $GITHUB_PATH
      - name: Print versions
        run: |
          java -version
          gpg --version
          ruby --version
          jekyll --version
      - name: Publish artifacts
        run: sbt 'show version' clean ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Update website
        run: sbt microsite/makeMicrosite microsite/publishMicrosite
