name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  cli:
    name: '[cli] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  core:
    name: '[core] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-core.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  codegen:
    name: '[codegen] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-codegen.yml
        env:
          GITHUB_TOKEN: 31480{{ secrets.GITHUB_TOKEN }}
  java-async-http:
    name: '[java-async-http] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-java-async-http.yml
        env:
          GITHUB_TOKEN: 31480{{ secrets.GITHUB_TOKEN }}
  java-dropwizard:
    name: '[java-dropwizard] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-java-dropwizard.yml
        env:
          GITHUB_TOKEN: 31480{{ secrets.GITHUB_TOKEN }}
  java-spring-mvc:
    name: '[java-spring-mvc] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-java-spring-mvc.yml
        env:
          GITHUB_TOKEN: 31480{{ secrets.GITHUB_TOKEN }}
  java-support:
    name: '[java-support] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-java-support.yml
        env:
          GITHUB_TOKEN: 31480{{ secrets.GITHUB_TOKEN }}
