name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  cli:
    name: '[cli] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  core:
    name: '[core] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: blast-hardcheese/release-drafter@v5.16.38
        with:
          config-name: release-drafter-core.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
